services:
  fcgi:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - shoots-db
      - redis-java
    volumes:
      - "./logs:/app/logs"
    networks:
      backend:

  httpd:
    image: "httpd:latest"
    ports:
      - "2909:80"
    volumes:
      - "./httpd.conf:/usr/local/apache2/conf/httpd.conf"
      - "./static:/var/www/"
    networks:
      backend:

  shoots-db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passsword
      POSTGRES_DB: shoots
    networks:
      backend:

  redis-java:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - ./redis-cache:/data
    command: redis-server --appendonly yes
    networks:
      backend:
networks:
  backend: