services:
  fcgi:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      backend:

  httpd:
    image: "httpd:latest"
    ports:
      - "2909:80"
    volumes:
      - "./httpd.conf:/usr/local/apache2/conf/httpd.conf"
      - "./static:/var/www/"
    networks:
      backend:
networks:
  backend: